// Generated by docs/make-run-script.py from docs/shots/hero.txt — do not edit.
//
// Every line below was printed by `nightaudit watch` during a real code_review
// of this repository. Editing this file by hand is how the landing page last
// ended up advertising output no command has ever produced; edit the capture
// and regenerate, or change the CLI and recapture. CI fails on a diff.

import type { ScriptLine } from "@/lib/run-script";

export const RUN_SCRIPT: readonly ScriptLine[] = [
  { kind: "banner", msg: "nightaudit · watching for runs — ctrl-c to stop", used: 0 },
  { kind: "meta", msg: "┌ nightaudit · code_review", detail: "claude_code · 00:09:36", used: 0 },
  { kind: "start", msg: "⏺ ~/nightshift", used: 0 },
  { kind: "prose", msg: "I'll start by exploring the repository structure to understand what this project is.", used: 0 },
  { kind: "tool", msg: "⏺ Glob", detail: "(pattern: **/*)", used: 0 },
  { kind: "result", msg: "⎿  .git/info/exclude (+100 lines)", used: 0 },
  { kind: "thinking", msg: "✻ thinking", used: 0 },
  { kind: "prose", msg: "The repo has a large `.venv` directory; let me find the actual project source.", used: 0 },
  { kind: "elide", msg: "94 lines", used: 0 },
  { kind: "med", msg: "🟠 MED  nightaudit/checks.py:167 · Stop passing the caller's shared `now` into each `r…", used: 0 },
  { kind: "med", msg: "🟠 MED  nightaudit/scheduler.py:307 · Move the `ledger.prune()`/`save()` pair inside t…", used: 0 },
  { kind: "low", msg: "🟡 LOW  nightaudit/report.py:419 · Either gate this line on `not failed_checks` or rew…", used: 0 },
  { kind: "low", msg: "🟡 LOW  nightaudit/cron.py:37 · `shlex.quote` the interpreter path here; a venv under …", used: 0 },
  { kind: "end", msg: "└ ✓ ok", detail: "2m52s · 4 findings", used: 1 },
] as const;
